# Generated by Django 2.2b1 on 2019-03-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thingpark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalogger',
            name='decoder',
            field=models.CharField(blank=True, choices=[('thingpark.AQBurkDecoder', 'thingpark.AQBurkDecoder'), ('thingpark.PaxcounterDecoder', 'thingpark.PaxcounterDecoder'), ('everynet.AQBurkDecoder', 'everynet.AQBurkDecoder'), ('everynet.PaxcounterDecoder', 'everynet.PaxcounterDecoder')], max_length=128),
        ),
        migrations.AlterField(
            model_name='datalogger',
            name='forwards',
            field=models.ManyToManyField(blank=True, related_name='thingpark_dataloggers', through='thingpark.DataloggerForward', to='broker.Forward', verbose_name='Data to forward'),
        ),
        migrations.AlterField(
            model_name='dataloggerforward',
            name='forward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thingpark_forwards', to='broker.Forward'),
        ),
    ]
